### ISSUE TITLE
`_auxLemma`s

### ISSUE THREAD

**Issue by marcusrossel** [nomeata/lean-calcify#9]
The following example:

```lean
import Mathlib

open Real Nat in
example (n : Nat) : Gamma (↑n + 1) * Gamma (↑n + 1) = (n ! * n !) := by
  calcify simp only [←cast_mul, Gamma_nat_eq_factorial]
```

... produces the following suggestion:

```lean
calc
  Gamma (↑n + 1) * Gamma (↑n + 1)
  _ = ↑n ! * Gamma (↑n + 1) := (congrArg (fun x => x * Gamma (↑n + 1)) (Gamma_nat_eq_factorial n))
  _ = ↑n ! * ↑n !           := (congrArg (fun x => ↑n ! * x) (Gamma_nat_eq_factorial n))
  _ = ↑(n ! * n !)          := (MWE.Basic._auxLemma.1 n ! n !)
  _ = ↑n ! * ↑n !           := (MWE.Basic._auxLemma.1 n ! n !).symm
```

Is looks like `cast_mul` is being turned into `MWE.Basic._auxLemma.1`, which breaks the proof.

**Comment by nomeata** [comment]
These aux lemmas are annoying :-)

Guess calcify should just unfold them?

**Comment by marcusrossel** [comment]
I have no clue where these aux lemmas come from. Do they correspond to `cast_mul` in some form?

**Comment by nomeata** [comment]
I don't know the details when that happens, but the simplifier sometimes put parts of the proof into a self contained theorem, as an optimization. So it makes sense for calcify to look though them.
